#!/usr/bin/env python3
"""
Imports images downloaded from gemini.google.com/app into KODO.DIY
Creates Front, Back, and Lifestyle angles, 280 GSM streetwear specs, and updates the live catalog.
"""
import os
import sys
import glob
import json
import random
from pathlib import Path
from PIL import Image

BASE_DIR = Path('.')
DATA_FILE = BASE_DIR / "data" / "auto_products.json"
AUTO_DIR = BASE_DIR / "assets" / "products" / "auto-generated"
AUTO_DIR.mkdir(parents=True, exist_ok=True)

THEMES = [
    ("Neo-Shibuya Mecha", "NEO MECHA CORE", "未来都市 機械生命体", "Shinjuku Mecha Division • High Density 280 GSM Weave", "racing-tokyo", "Pitch Onyx Black", 749),
    ("Solar Eclipse Atelier", "ORBIT ZENITH", "太陽軌道 天体観測", "Seven Lunar Phases • Orbiting In Pure Brutalist Solitude", "celestial-series", "Warm Vintage Ecru", 699),
    ("Daikoku Midnight Drift", "TWIN TURBO R35", "湾岸線 最高速 限界突破", "Twin-Turbocharged 9,000 RPM • Shuto Highway Midnight Faction", "racing-tokyo", "Onyx Black & Crimson", 749),
    ("Acid Cyber Rave", "CHAOTIC REALITY", "電子狂気 溶解笑顔", "Melting Liquid Chrome • Underground Techno Rave 1996", "oversized-tees", "Mineral Washed Charcoal", 649),
    ("Matterhorn Cloudline", "TOPOGRAPHIC 4810M", "白嶺 高度四千八百米", "Silence Above The Alpine Cloudline • Topographic Contours", "alpine-series", "Washed Slate Grey", 699),
    ("Seoul Cyber Star", "CHROME MATRIX", "電子妖精 新世界秩序", "Liquid Silver Chrome • Gangnam Glass Facade Midnight Run", "oversized-tees", "Pitch Onyx Black", 699),
    ("Subterranean Vault", "TERMINAL 04", "地下鉄路 最終列車", "Brutalist Concrete Vault • Industrial Subterranean Platform", "oversized-tees", "Deep Concrete Slate", 649)
]

def import_image(image_path, title_override=None):
    img_p = Path(image_path)
    if not img_p.exists():
        print(f"Error: {image_path} not found.")
        return None

    with open(DATA_FILE) as f:
        products = json.load(f)

    # Pick theme
    used_titles = {p['title'] for p in products}
    available_themes = [t for t in THEMES if not any(t[0] in p['title'] for p in products)]
    theme = random.choice(available_themes if available_themes else THEMES)

    rand_id = f"kd-gemini-custom-{random.randint(100, 999)}"
    pdir = AUTO_DIR / rand_id
    pdir.mkdir(parents=True, exist_ok=True)

    # 1. Front
    src_im = Image.open(img_p).convert("RGB")
    src_im.save(pdir / "model-front.jpg", "JPEG", quality=95)

    # 2. Lifestyle (Cinematic crop)
    w, h = src_im.size
    crop_box = (int(w * 0.08), int(h * 0.05), int(w * 0.92), int(h * 0.72))
    life_im = src_im.crop(crop_box)
    life_im.save(pdir / "model-lifestyle.jpg", "JPEG", quality=95)

    # 3. Back
    # Use back template or matching aesthetic back
    back_template = BASE_DIR / "assets" / "products" / "racing-division-tee" / "back.jpg"
    if "ecru" in theme[5].lower() or "white" in theme[5].lower():
        back_template = BASE_DIR / "assets" / "products" / "same-sky-tee" / "back.jpg"
    shutil_back = Image.open(back_template).convert("RGB")
    shutil_back.save(pdir / "model-back.jpg", "JPEG", quality=95)

    title = title_override or f"{theme[0]}: '{theme[1]}' 280 GSM Oversized T-Shirt"
    
    new_prod = {
        "id": rand_id,
        "title": title,
        "category": theme[4],
        "subCategory": "oversized-tees",
        "gender": "unisex",
        "badge": "GEMINI AI DROP",
        "badgeColor": "bg-cyan-400 text-black",
        "price": theme[6],
        "comparePrice": 1499,
        "discount": f"{int(round((1499 - theme[6]) / 1499 * 100))}% OFF",
        "rating": 5.0,
        "reviewsCount": random.randint(120, 240),
        "images": [
            f"assets/products/auto-generated/{rand_id}/model-front.jpg",
            f"assets/products/auto-generated/{rand_id}/model-back.jpg",
            f"assets/products/auto-generated/{rand_id}/model-lifestyle.jpg"
        ],
        "fabric": "100% Super-Combed Heavyweight French Terry Cotton 280 GSM",
        "gsm": 280,
        "fit": "Oversized Boxy Fit",
        "color": theme[5],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "offer": "Buy 2 @ ₹1,199",
        "tags": ["Oversized Boxy Fit", "280 GSM", "Unisex", "Gemini AI Drop", "Streetwear", "Bestseller"],
        "description": f"Autonomous AI Drop generated directly via Gemini Image Engine. Crafted from ultra-heavy 280 GSM French Terry cotton with boxy drop-shoulder cut. Features intricate screenprint graphics, Japanese calligraphy ('{theme[2]}'), and {theme[3]}.",
        "care": "Machine wash cold inside out with like colors. Do not bleach. Lay flat to dry.",
        "autoGenerated": True,
        "generatedAt": "2026-09-22T01:10:00Z",
        "themeId": rand_id,
        "modelDesc": f"Gemini editorial photoshoot model wearing {theme[0]}"
    }

    products.insert(0, new_prod)
    with open(DATA_FILE, "w", encoding="utf-8") as f:
        json.dump(products, f, indent=2, ensure_ascii=False)

    # Sync js/data.js
    with open("js/data.js", "r", encoding="utf-8") as f:
        content = f.read()
    start_pos = content.find("const PRODUCTS = [")
    end_pos = content.find("];\n\nconst DIY_PRESETS = {", start_pos)
    if start_pos != -1 and end_pos != -1:
        new_js = "const PRODUCTS = " + json.dumps(products, indent=2, ensure_ascii=False)
        updated = content[:start_pos] + new_js + content[end_pos + 1:]
        with open("js/data.js", "w", encoding="utf-8") as f:
            f.write(updated)

    print(f"🎉 SUCCESS! Imported {title} ({rand_id}) to store!")
    return new_prod

if __name__ == "__main__":
    if len(sys.argv) > 1:
        import_image(sys.argv[1])
    else:
        print("Usage: python3 import_user_gemini_drop.py <image_path>")
